#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2026 Sebastian Kügler <sebas@kde.org>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL

"""Regenerates src/gui/qml/icons/seabass_soundbass.svg with the fish clip
baked into the bar geometry.

The design is equalizer bars clipped by a fish silhouette. Qt's SVG
renderer (QtSvg, used by Qt Quick's Image, QIcon and therefore the window
and taskbar icon) does not apply <clipPath>, so it drew the bars at full
height and the logo looked stretched vertically. Every bar is therefore
emitted as the polygon of (bar rectangle intersected with the fish
outline), with its gradient pinned to the original bar's top and bottom
in user space so the colours are unchanged. Run from the repository root;
no dependencies beyond the standard library.
"""

from pathlib import Path

# The fish outline from the original design, in its own units (x -20..20,
# y -14..14), then translate(100,100) scale(4.3) into the 200x200 viewBox.
SCALE = 4.3
OFFSET = 100.0
# M20,0 C20,7 12,11 2,9 C-2,14 -14,12 -20,4 L-14,0 L-20,-4 C-14,-12 -2,-14 2,-9 C12,-11 20,-7 20,0 Z
CURVES = [
    ((20, 0), (20, 7), (12, 11), (2, 9)),
    ((2, 9), (-2, 14), (-14, 12), (-20, 4)),
    "L(-14,0)",
    "L(-20,-4)",
    ((-20, -4), (-14, -12), (-2, -14), (2, -9)),
    ((2, -9), (12, -11), (20, -7), (20, 0)),
]
BARS = [  # x, y, width, height, gradient
    (20, 75, 12, 50, "gradCurrent"),
    (36, 55, 12, 90, "gradKelp"),
    (52, 35, 12, 130, "gradCurrent"),
    (68, 20, 12, 160, "gradKelp"),
    (84, 25, 12, 150, "gradCurrent"),
    (100, 20, 12, 160, "gradKelp"),
    (116, 35, 12, 130, "gradCurrent"),
    (132, 55, 12, 90, "gradKelp"),
    (148, 75, 12, 50, "gradCurrent"),
    (164, 90, 12, 20, "gradKelp"),
]
GRADIENTS = {"gradCurrent": ("#74cdf5", "#123a52"), "gradKelp": ("#5be0c0", "#0b6852")}


def fish_polygon(steps=64):
    pts = []
    for seg in CURVES:
        if isinstance(seg, str):
            x, y = eval(seg[1:])
            pts.append((x, y))
            continue
        p0, p1, p2, p3 = seg
        for i in range(1, steps + 1):
            t = i / steps
            u = 1 - t
            x = u**3 * p0[0] + 3 * u**2 * t * p1[0] + 3 * u * t**2 * p2[0] + t**3 * p3[0]
            y = u**3 * p0[1] + 3 * u**2 * t * p1[1] + 3 * u * t**2 * p2[1] + t**3 * p3[1]
            pts.append((x, y))
    return [(OFFSET + x * SCALE, OFFSET + y * SCALE) for x, y in pts]


def clip(polygon, x0, y0, x1, y1):
    """Sutherland-Hodgman against an axis-aligned rectangle."""
    def clip_edge(poly, inside, intersect):
        out = []
        if not poly:
            return out
        prev = poly[-1]
        for cur in poly:
            if inside(cur):
                if not inside(prev):
                    out.append(intersect(prev, cur))
                out.append(cur)
            elif inside(prev):
                out.append(intersect(prev, cur))
            prev = cur
        return out

    def at_x(x):
        return lambda a, b: (x, a[1] + (b[1] - a[1]) * (x - a[0]) / (b[0] - a[0]))

    def at_y(y):
        return lambda a, b: (a[0] + (b[0] - a[0]) * (y - a[1]) / (b[1] - a[1]), y)

    poly = polygon
    poly = clip_edge(poly, lambda p: p[0] >= x0, at_x(x0))
    poly = clip_edge(poly, lambda p: p[0] <= x1, at_x(x1))
    poly = clip_edge(poly, lambda p: p[1] >= y0, at_y(y0))
    poly = clip_edge(poly, lambda p: p[1] <= y1, at_y(y1))
    return poly


def main():
    fish = fish_polygon()
    out = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">',
           '  <!--',
           '    "Sound Bass": the Seabass app icon / watermark. A fish silhouette',
           '    made of vertical equalizer bars, in the app\'s Current/Kelp palette.',
           '    Generated by tools/flatten_logo.py: the fish clip is baked into',
           '    each bar\'s geometry because Qt\'s SVG renderer ignores <clipPath>',
           '    (it drew the bars unclipped, so the logo looked stretched). Edit',
           '    the generator, not this file.',
           '  -->',
           '  <defs>']
    for i, (x, y, w, h, grad) in enumerate(BARS):
        top, bottom = GRADIENTS[grad]
        out.append(f'    <linearGradient id="bar{i}" gradientUnits="userSpaceOnUse" x1="0" y1="{y}" x2="0" y2="{y + h}">')
        out.append(f'      <stop offset="0" stop-color="{top}"/>')
        out.append(f'      <stop offset="1" stop-color="{bottom}"/>')
        out.append('    </linearGradient>')
    out.append('  </defs>')
    for i, (x, y, w, h, grad) in enumerate(BARS):
        poly = clip(fish, x, y, x + w, y + h)
        if len(poly) < 3:
            continue
        d = "M" + " L".join(f"{px:.2f},{py:.2f}" for px, py in poly) + " Z"
        out.append(f'  <path d="{d}" fill="url(#bar{i})"/>')
    ex, ey = OFFSET + 10 * SCALE, OFFSET - 2.4 * SCALE
    out.append(f'  <circle cx="{ex:.2f}" cy="{ey:.2f}" r="{4.2 * SCALE:.2f}" fill="#eef6fb"/>')
    out.append(f'  <circle cx="{OFFSET + 11.575 * SCALE:.2f}" cy="{ey:.2f}" r="{2.0 * SCALE:.2f}" fill="#0d2b36"/>')
    out.append('</svg>')
    Path("src/gui/qml/icons/seabass_soundbass.svg").write_text("\n".join(out) + "\n")
    print(f"wrote {len(BARS)} bars")


if __name__ == "__main__":
    main()
